services:
  mongo:
    image: mongo:latest
    container_name: mongo-hotel-booker
    volumes:
      - type: bind
        source: ./mongo-init.js
        target: /docker-entrypoint-initdb.d/mongo-init.js
        read_only: true
    ports:
      - "27017:27017"
    restart: no

volumes:
  mongo-data:
    driver: local